version: '3'

services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: haitun
      MYSQL_PASSWORD: cFzMv0Ha^&EIz&g6Va
      MYSQL_ROOT_PASSWORD: cFzMv0Ha^&EIz&g6Va
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=47.106.115.51
#      - PMA_HOST=wordpressadmin_mynetwork
      - PMA_USER=haitun
      - PMA_PASSWORD=cFzMv0Ha^&EIz&g6Vb
    networks:
      - mynetwork
    depends_on:
      - mysql

networks:
  mynetwork:
    driver: bridge
